// <auto-generated />
namespace ListMed.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class foto11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(foto11));
        
        string IMigrationMetadata.Id
        {
            get { return "201811050257133_foto11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
