// <auto-generated />
namespace ListMed.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Localidade_acerto2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Localidade_acerto2));
        
        string IMigrationMetadata.Id
        {
            get { return "201810280429201_Localidade_acerto2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
