// <auto-generated />
namespace ListMed.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cidadebairro : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cidadebairro));
        
        string IMigrationMetadata.Id
        {
            get { return "201811050024112_cidadebairro"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
